@startuml
skinparam classFontName Dialog
@startmindmap

<style>
node {
    LineThickness 2.5
    MaximumWidth 250
}

rootNode {
    LineColor red
}

leafNode {
    LineStyle 8.0;3.0
    Padding 3
}

</style>

* <b>Безопасность данных</b>
left side
**:<b>Публичные данные</b>

* Новости и акции на сайте компании
;
***:<b>Риск:</b> Искажение данных <color:orange>[<b>значительный</b>]</color>
<i>Например, искажения в ценах в акциях на сайте может оттолкнуть потецниальных клиентов и нанести репутационные потери</i>
;

**:<b>Внутренние данные</b>

* Фонд жилья для подбора и бронирования
* Данные об онлайн турах
* Данные о ремонтах для собственников
* Информация/услуги от УК для собственников
;

***:<b>Риск:</b> Утечка данных <color:green>[<b>незначительный</b>]</color>
<i>Утечка данных выглядит незначительным риском, если персональные данные клиентов/собственников и данные о сделках хранятся в других БД (конфиденциальных и секретных)</i>
;
***:<b>Риск:</b> Потеря данных <color:red>[<b>критический</b>]</color>
<i>Например, потрея БД с объектами недвижимости привидет к невозможности использования сервиса по подбору и бронированию</i>
;
***:<b>Риск:</b> Искажение данных <color:orange>[<b>значительный</b>]</color>
<i>Например, искажения в ценах на объекты недвижимости может привести к отказу от сделки</i>
;

right side
**: <b>Конфиденциальные данные</b>

* Персональные данные клиентов/собственников
* Финансовая аналитика
* Данные умного дома
;
***:<b>Риск:</b> Утечка данных <color:red>[<b>критический</b>]</color>
<i>Утечка данной категории данных может быть критической, т.к. повлечет за собой штрафы, репутационные издержки</i>
;
***:<b>Риск:</b> Потеря данных <color:red>[<b>критический</b>]</color>
<i>Потрея данных приведет к невозможности работы критически важных сервисов компании:
<i>заключение сделок, регистрация в госорганах и т.п.
;
***:<b>Риск:</b> Искажение данных и некачестевенные данные <color:red>[<b>критический</b>]</color>
*<i>Искажение данной категори данных может повлечь за собой невозможность заключения сделок (если будут искажения в персональных данных клиентов.
*<i>Искажение в финансовой аналитике может повлечь неправльные расчеты финансовых показателей компании
;


**: <b>Секретные данные</b>

* Платежные данные
* Данные по регистрации сделок в госорганах
* Данные для контроля запирающих квартиру устройств
;
***:<b>Риск:</b> Утечка данных <color:red>[<b>критический</b>]</color>
*<i>Утечка данной категории данных будет критической, т.к. повлечет за собой большие штрафы, репутационные издержки и прямые убытки</i>
*<i>Также есть риск, что злоумышленник сможет попасть в квартиру пользователя сервиса умного дома
;
***:<b>Риск:</b> Потеря данных <color:red>[<b>критический</b>]</color>
<i>Потрея данных приведет к невозможности работы критически важных сервисов компании:
<i>онлайн оплата, регистрация в госорганах, пользователи умного дома не смогут попасть домой
;
***:<b>Риск:</b> Искажение данных и некачестевенные данные <color:red>[<b>критический</b>]</color>
*<i>Искажение платежных данных может привести к сбоям в оплате
*<i>Искажение данных о регистрации сделок в госорганах может повлечь к большим штрафам и репутационным проблемам
;

@endmindmap
@enduml