apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-resource-write-global
subjects:
- kind: Group
  name: DevOps
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-resource-write
  apiGroup: rbac.authorization.k8s.io 